name: CairoSVG
include: dependencies.yml
options:
  bundleIdPrefix: com.brightdigit
  deploymentTarget: 
    macOS: 10.15
targets:
  CairoSVG:
    type: framework
    platform: macOS
    sources: 
        - path: Sources/CairoSVG
          group: Sources
    postBuildScripts:
      - script: "\"${SRCROOT}/scripts/fix_dylibs.sh\" \"${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}\""
      - script: "\"${SRCROOT}/scripts/codesign-framework.sh\""
    settings: 
        HEADER_SEARCH_PATHS: $(SRCROOT)/Dependencies/**
        LIBRARY_SEARCH_PATHS: $(SRCROOT)/Dependencies/**
        LD_RUNPATH_SEARCH_PATHS: "@loader_path/Frameworks"
        CODE_SIGN_IDENTITY: ${inherited}
  CairoSVGTests:
    type: bundle.unit-test
    platform: macOS
    sources: 
        - path: Tests/CairoSVGTests
          group: Tests
    dependencies:
        - target: CairoSVG
