name: CairoSVG
include: dependencies.yml
options:
  bundleIdPrefix: com.brightdigit
targets:
  CairoSVG:
    type: framework
    platform: macOS
    sources: [frameworks/cairosvg]
    postBuildScripts:
      - script: "${SRCROOT}/scripts/fix_dylibs.sh" "${TARGET_BUILD_DIR}/${EXECUTABLE_PATH}"
    settings: 
        HEADER_SEARCH_PATHS: $(SRCROOT)/Dependencies/**
        LIBRARY_SEARCH_PATHS: $(SRCROOT)/Dependencies/**
        LD_RUNPATH_SEARCH_PATHS: "@loader_path/Frameworks"