name: CairoSVG
options:
  bundleIdPrefix: com.brightdigit
targets:
  CairoSVG:
    type: framework
    platform: macOS
    deploymentTarget: "10.6"
    sources: [frameworks/cairosvg]
    dependencies:
    - sdk: Dependencies/libpng/1.6.37/lib/libpng16.16.dylib
    - sdk: Dependencies/pixman/0.40.0/lib/libpixman-1.0.40.0.dylib
    - sdk: Dependencies/freetype/2.10.1/lib/libfreetype.6.dylib
    - sdk: Dependencies/pango/1.44.7/lib/libpango-1.0.0.dylib
    - sdk: Dependencies/pango/1.44.7/lib/libpangoft2-1.0.0.dylib
    - sdk: Dependencies/pango/1.44.7/lib/libpangocairo-1.0.0.dylib
    - sdk: Dependencies/gdk-pixbuf/2.40.0_1/lib/libgdk_pixbuf-2.0.0.dylib
    - sdk: Dependencies/icu4c/66.1/lib/libicuuc.66.1.dylib
    - sdk: Dependencies/icu4c/66.1/lib/libicudata.66.1.dylib
    - sdk: Dependencies/icu4c/66.1/lib/libicutest.66.1.dylib
    - sdk: Dependencies/icu4c/66.1/lib/libicuio.66.1.dylib
    - sdk: Dependencies/icu4c/66.1/lib/libicui18n.66.1.dylib
    - sdk: Dependencies/icu4c/66.1/lib/libicutu.66.1.dylib
    - sdk: Dependencies/icu4c/67.1/lib/libicudata.67.1.dylib
    - sdk: Dependencies/icu4c/67.1/lib/libicutest.67.1.dylib
    - sdk: Dependencies/icu4c/67.1/lib/libicuuc.67.1.dylib
    - sdk: Dependencies/icu4c/67.1/lib/libicuio.67.1.dylib
    - sdk: Dependencies/icu4c/67.1/lib/libicutu.67.1.dylib
    - sdk: Dependencies/icu4c/67.1/lib/libicui18n.67.1.dylib
    - sdk: Dependencies/harfbuzz/2.6.6/lib/libharfbuzz-subset.0.dylib
    - sdk: Dependencies/harfbuzz/2.6.6/lib/libharfbuzz-gobject.0.dylib
    - sdk: Dependencies/harfbuzz/2.6.6/lib/libharfbuzz.0.dylib
    - sdk: Dependencies/harfbuzz/2.6.6/lib/libharfbuzz-icu.0.dylib
    - sdk: Dependencies/glib/2.64.3/lib/libglib-2.0.0.dylib
    - sdk: Dependencies/glib/2.64.3/lib/libgobject-2.0.0.dylib
    - sdk: Dependencies/glib/2.64.3/lib/libgmodule-2.0.0.dylib
    - sdk: Dependencies/glib/2.64.3/lib/libgthread-2.0.0.dylib
    - sdk: Dependencies/glib/2.64.3/lib/libgio-2.0.0.dylib
    - sdk: Dependencies/graphite2/1.3.14/lib/libgraphite2.3.2.1.dylib
    - sdk: Dependencies/cairo/1.16.0_3/lib/libcairo.2.dylib
    - sdk: Dependencies/cairo/1.16.0_3/lib/libcairo-gobject.2.dylib
    - sdk: Dependencies/cairo/1.16.0_3/lib/libcairo-script-interpreter.2.dylib
    - sdk: Dependencies/fribidi/1.0.9/lib/libfribidi.0.dylib
    - sdk: Dependencies/fontconfig/2.13.1/lib/libfontconfig.1.dylib
    - sdk: Dependencies/libcroco/0.6.13_1/lib/libcroco-0.6.3.dylib
    - sdk: Dependencies/gettext/0.20.2_1/lib/libgettextpo.0.dylib
    - sdk: Dependencies/gettext/0.20.2_1/lib/libgettextlib-0.20.2.dylib
    - sdk: Dependencies/gettext/0.20.2_1/lib/libtextstyle.0.dylib
    - sdk: Dependencies/gettext/0.20.2_1/lib/libintl.8.dylib
    - sdk: Dependencies/gettext/0.20.2_1/lib/libasprintf.0.dylib
    - sdk: Dependencies/gettext/0.20.2_1/lib/libgettextsrc-0.20.2.dylib
    - sdk: Dependencies/librsvg/2.48.4/lib/librsvg-2.2.dylib
    - sdk: Dependencies/pcre/8.44/lib/libpcre.1.dylib
    - sdk: Dependencies/pcre/8.44/lib/libpcreposix.0.dylib
    - sdk: Dependencies/pcre/8.44/lib/libpcrecpp.0.dylib
    - sdk: Dependencies/pcre/8.44/lib/libpcre16.0.dylib
    - sdk: Dependencies/pcre/8.44/lib/libpcre32.0.dylib
    - sdk: Dependencies/libffi/3.3/lib/libffi.7.dylib