name: CairoSVG
include: dependencies.yml
options:
  bundleIdPrefix: com.brightdigit
targets:
  CairoSVG:
    type: framework
    platform: macOS
    deploymentTarget: "10.6"
    sources: [frameworks/cairosvg]
    settings: 
        HEADER_SEARCH_PATHS: Dependencies/**
        LIBRARY_SEARCH_PATHS: Dependencies/**