name: versioning

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test aPI
      run: |
        curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | xargs -I {}  $GITHUB_WORKSPACE/semver bump patch {}
    - name: Bump version and push tag
      run: |
        curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | xargs -I {}  $GITHUB_WORKSPACE/semver bump patch {}
        TAG_NAME=$(curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | xargs -I {}   $GITHUB_WORKSPACE/semver bump patch {})
        echo "::set-output name=tag::$TAG_NAME"
      id: semver
    - name: Output Tag
      run: echo ${{ steps.semver.outputs.tag }}
