name: versioning

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Bump version and push tag
      run: curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases
      id: semver
