name: versioning

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Bump version and push tag
      run: |
        curl https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | xargs -I {}  ./semver bump patch {}
        TAG_NAME=$(curl https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | xargs -I {}  ./semver bump patch {})
        echo "::set-output name=tag::$TAG_NAME"
      id: semver
    - name: Output Tag
      run: echo ${{ steps.semver.outputs.tag }}
