name: XCFramework

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Xcode Project
      run: ./prepare.sh
    - name: Build Framework
      run: ./build.sh
    - name: Install JQ
      run: brew install jq
    - name: Bump version and push tag
      run: curl https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | xargs -I {}  ./semver bump patch {}
